color = input("What is your favorite color? ")
plural_noun = input("What is your favorite plural noun? ")
celebrity = input("Who is your favorite celebrity? ")
print("Roses are " + color)
print(plural_noun + " are blue")
print("I love " + celebrity)